services:
  backend:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://peak-test:peak-test@postgres:5432/peak-test

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: peak-test
      POSTGRES_PASSWORD: peak-test
      POSTGRES_DB: peak-test
    ports:
      - '5432:5432'
